improve require(), add require_tree()

diff --git a/lib/core b/lib/core
--- a/lib/core
+++ b/lib/core
@@ -7,5 +7,20 @@ exists() {
 }
 
 require() {
-  source $SCRIPT_HOME/$1
+  if exists $SCRIPT_HOME/$1 ; then
+    source $SCRIPT_HOME/$1
+  else
+    if [ "$2" != "-f" ] ; then
+      echo "Could not source script at $SCRIPT_HOME/$1, exiting."
+      exit 64
+    fi
+  fi
+}
+
+require_tree() {
+  if exists $SCRIPT_HOME/$1 ; then
+    for file in $SCRIPT_HOME/$1/* ; do
+      [ -f $file ] && source $file
+    done
+  fi
 }
